let
  Source = SharePoint.Files("https://wtwonlineap.sharepoint.com/sites/tctnonclient_APACSCMDat", [ApiVersion = 15]),
  #"Filtered rows" = Table.SelectRows(Source, each [Folder Path] = "https://wtwonlineap.sharepoint.com/sites/tctnonclient_APACSCMDat/Data Library/Client Baseline/02. Raw Data/GSWin/"),
  Navigation = #"Filtered rows"{[Name = "GSWin Data.xlsx", #"Folder Path" = "https://wtwonlineap.sharepoint.com/sites/tctnonclient_APACSCMDat/Data Library/Client Baseline/02. Raw Data/GSWin/"]}[Content],
  #"Imported Excel workbook" = Excel.Workbook(Navigation, null, true),
  #"Navigation 1" = #"Imported Excel workbook"{[Item = "PolicyReport", Kind = "Sheet"]}[Data],
  #"Promoted headers" = Table.PromoteHeaders(#"Navigation 1", [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Batch", type text}, {"Branch Name", type text}, {"ClientID", type text}, {"Client Name", type text}, {"Client Type", type text}, {"Parent Client", type text}, {"Policy Number", type text}, {"Endor Number", type text}, {"Policy Type", type text}, {"Policy Type Name", type text}, {"Renewable", type text}, {"New/ #(lf)Renew", type text}, {"PrevPolicyNbr", type text}, {"Previous Batch Number", type text}, {"Issue Date", type date}, {"Inception Date", type date}, {"Expiry Date", type date}, {"Cury Code", type text}, {"Premium", type number}, {"Premium VND", type number}, {"Premium USD", type number}, {"Premium EUR", type number}, {"Premium Tax in VND", type number}, {"CommRate", type number}, {"Comm Amt", type number}, {"CommAmt VND", type number}, {"CommAmt USD", type number}, {"CommAmt EUR", type number}, {"TPARate", type number}, {"TPAAmt", type number}, {"TPAAmt VND", type number}, {"TPAAmt USD", type number}, {"TPAAmt EUR", type number}, {"NonTPAAmt", type nullable number}, {"NonTPAAmt VND", type nullable number}, {"NonTPAAmt USD", type number}, {"NonTPAAmt EUR", type number}, {"CoBroker Name", type text}, {"Co-Broker Fee", type nullable number}, {"Co-Broker Fee In VND", type nullable number}, {"Co-Broker Fee In USD", type number}, {"Co-Broker Fee In EUR", type nullable number}, {"Other Fee", type nullable number}, {"Other Fee In VND", type nullable number}, {"Other Fee In USD", type number}, {"Other Fee In EUR", type number}, {"InsurerID", type text}, {"Insurer Name", type text}, {"CoInsuranceShare", type text}, {"ManagerID", type text}, {"TeamID", type text}, {"CreateUserID", type text}, {"VerifyUserID", type text}, {"Report Date", type date}, {"Report Year", Int64.Type}, {"RP Amt", type number}, {"RP Amt VND", type number}, {"RP Amt USD", type number}, {"RP Amt EUR", type number}, {"Balance Amt", type number}, {"Balance Amt VND", type nullable number}, {"Balance Amt USD", type nullable number}, {"Balance Amt EUR", type nullable number}, {"Inward Type", type text}, {"Country", type text}, {"Comm Tax in VND", type number}, {"TPA Tax in VND", type number}, {"None TPA Tax in VND", Int64.Type}, {"Cobroker Income Type", type text}, {"Total Brokerage in VND", type number}, {"Total Brokerage in USD", type number}, {"Division", type text}, {"Willis Line", type text}, {"Insurer Group", type text}, {"Insurer Group Name", type text}, {"Kind of Owner", type text}, {"Cross Sale Source", type text}, {"Cross Sale by", type text}, {"Client Address", type text}, {"GCID", type text}, {"Remark", type text}, {"Nationalty", type text}, {"Industry", type text}, {"Sub Industry", type text}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Column87"}),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Removed columns", {{"LISA RefNbr", type text}, {"Report Year", type text}, {"InstallNo", type text}})
in
  #"Changed column type 1"