let
  Source = SharePoint.Files("https://wtwonlineap.sharepoint.com/sites/tctnonclient_APACSCMDat", [ApiVersion = 15]),
  #"Filtered rows" = Table.SelectRows(Source, each [Folder Path] = "https://wtwonlineap.sharepoint.com/sites/tctnonclient_APACSCMDat/Data Library/Client Baseline/02. Raw Data/Arias/"),
  Navigation = #"Filtered rows"{[Name = "Arias Revenue.xlsx", #"Folder Path" = "https://wtwonlineap.sharepoint.com/sites/tctnonclient_APACSCMDat/Data Library/Client Baseline/02. Raw Data/Arias/"]}[Content],
  #"Imported Excel workbook" = Excel.Workbook(Navigation, null, true),
  #"Navigation 1" = #"Imported Excel workbook"{[Item = "Revenuev2", Kind = "Sheet"]}[Data],
  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column22", type text}, {"Column23", type text}, {"Column26", type text}, {"Column27", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type text}, {"Column45", type text}, {"Column46", type text}, {"Column47", type text}, {"Column48", type text}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}}),
  #"Removed top rows" = Table.Skip(#"Changed column type", 1),
  #"Promoted headers" = Table.PromoteHeaders(#"Removed top rows", [PromoteAllScalars = true]),
  #"Changed column type 1" = Table.TransformColumnTypes(#"Promoted headers", {{"保険始期", type date}, {"T900_EFDATE", type date}, {"保険終期", type date}, {"T900_EXPIDATE", type date}, {"異動保険始期", type date}, {"異動保険終期", type date}, {"請求書発行日", type date}, {"請求書番号", type text}, {"入金日", type date}, {"返戻日", type date}, {"分割回目", type nullable number}, {"分割回数", type nullable number}, {"収益認識日", type date}, {"収益区分", type nullable number}, {"FEE Domestic", type nullable number}, {"FEE Overseas", type nullable number}, {"集金区分", type nullable number}, {"保険料", type nullable number}, {"手数料率", type nullable number}, {"手数料（税抜)", type nullable number}, {"共保代理店扱", type nullable number}, {"共保精算方式", type nullable number}, {"GCID", type text}, {"Policy No", type text}})
in
  #"Changed column type 1"